### ISSUE TITLE
Macro to set shortcut icon and color

### ISSUE THREAD

**Issue by pfgithub** [pfgithub/shortcutslang#34]
`@seticon <shortcuts js icon name>`
`@setcolor <shortcuts js color name>`

or something

shortcutsjs has all the icons

https://docs.shortcuts.fun/metadata/icon

**Comment by atnbueno** [comment]
Right now that link doesn't work, but you can go to https://docs.shortcuts.fun/ and then click "Shortcut Icon" (under "Metadata") in the sidebar.

More specific sources of metadata information:
- Colors in 32-bit RRGGBBAA format: https://github.com/joshfarrant/shortcuts-js/blob/master/src/meta/colors.ts
- Glyph names and codepoints: https://github.com/joshfarrant/shortcuts-js/blob/master/src/meta/glyphs.ts
- SVG paths of glyphs: https://github.com/joshfarrant/shortcuts-js/blob/master/docs/src/components/Docs/Metadata/ShortcutIcon/iconGlyphs.js

Glyphs order is the same as in the iOS app (columns of three and then to the right). Colors too, but rows of five first then down.
