### ISSUE TITLE
Separate CLI into its own package

### ISSUE THREAD

**Issue by haykam821** [pfgithub/shortcutslang#38]
Both `yargs` and `chalk` are only used for the CLI, but in some cases I am only using the Node.js API. Personally, I think it would be better to split this into a `scpl-cli` package and link between the two.

**Comment by pfgithub** [comment]
Would you have to do a seperate `npm i -g scpl-cli` to get the scpl command or is there a way to include it in the scpl package when installed globally?

**Comment by haykam821** [comment]
Running `npm i -g scpl-cli scpl` would dedupe the packages, but `npm i -g scpl-cli` wouldn't directly include `scpl`. However, I think that's better because I think people will use one or the other.

**Comment by haykam821** [comment]
Here is a visualization of the ScPL and ScPL CLI dependencies (using [this tool](https://npm.anvaka.com/#/view/2d/scpl)):

![ScPL dependency visualization](https://user-images.githubusercontent.com/24855774/55109674-bd2dc080-50ac-11e9-8604-3f696276e1f6.png)

**Comment by pfgithub** [comment]
I didn't realise yargs was that big, I don't even use any real features from it and could probably be using minimist instead. The cli package is now `scpl-cli` and the `scpl` package is only for scpl itself.
